version: "3"
services:
  api:
    build: ./api
    command: nodemon server.js
    volumes:
      - ./api/:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"